development:
  adapter: postgresql
  encoding: unicode
  database: galleryconnect_development
  pool: 5
  username: nicholasbundy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: galleryconnect_test
  pool: 5
  username: nicholasbundy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gallyerconnect_production
  pool: 5
  username: nicholasbundy
  password:
